/* Ctrl + Shift + P para abrir los comandos y usaremos el Paste JSON as Code para crear nuestra interfaz basándonos en la respuesta del servicio de pokeAPI.
Para que esto funcione, necesitamos tener copiada la respuesta de dicho servicio para que el comando genere la interfaz correctamente. */
// Generated by https://quicktype.io

export interface PokeResponse {
  count: number;
  next: string;
  previous: null;
  results: Result[];
}

export interface Result {
  name: string;
  url: string;
}
